%include('header_init.tpl', heading='Import Excel file')



<form action="/upload" method="post" enctype="multipart/form-data">
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" name="upload">
    <p class="help-block">Only unmodified .xlsx files generated by ASSESS 2 are supported.</p>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>



%include('header_end.tpl')

%include('js.tpl')

<script>$('li.import').addClass("active");</script>


</body>

</html>
