%include('header_init.tpl', heading='Import Excel file')



<form action="/upload" method="post" enctype="multipart/form-data">
  <div class="mb-3">
    <label class="form-label" for="customFile">File input</label>
    <input type="file" name="upload" class="form-control" id="customFile">
    <p class="help-block">Only unmodified .xlsx files generated by ASSESS 2 are supported.</p>
  </div>
  <button type="submit" class="btn btn-outline-dark">Submit</button>
</form>



%include('header_end.tpl')

%include('js.tpl')

<script>$('li.import').addClass("active");</script>


</body>

</html>
